name: Refresh filtered ICS

on:
  schedule:
    - cron: "0 */12 * * *"   # every 12 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install icalendar requests

      - name: Run filter
        env:
          SOURCE_ICS_URL: ${{ secrets.SOURCE_ICS_URL }}
          RULES_JSON: ${{ secrets.RULES_JSON }}
          OUTPUT_OUTLOOK: docs/outlook.ics
          OUTPUT_MAGIC: docs/magicmirror.ics
        run: |
          python scripts/filter_ics.py

      - name: Commit & push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add docs/outlook.ics docs/magicmirror.ics
            git commit -m "Update filtered ICS (Outlook & MagicMirror)"
            git push
          fi
