name: Refresh filtered ICS

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */4 * * *"  # every 4 hours

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install icalendar requests

      - name: Build ICS files
        env:
          SOURCE_ICS_URL: ${{ secrets.SOURCE_ICS_URL }}
          RULES_JSON: ${{ secrets.RULES_JSON }}
        run: |
          python scripts/filter_ics.py
          echo "---- ls docs ----"
          ls -l docs || true
          echo "---- head outlook ----"
          head -n 20 docs/outlook.ics
          echo "---- head magic ----"
          head -n 20 docs/magicmirror.ics

      - name: Commit outputs
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/outlook.ics docs/magicmirror.ics
          git commit -m "chore: update ICS (outlook & magicmirror) [skip ci]" || echo "No changes to commit"
          git push
